# Generated by Django 5.2.6 on 2025-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='00000-000', max_length=100),
            preserve_default=False,
        ),
    ]
