# Generated by Django 5.2.6 on 2025-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('has_breeds', models.BooleanField(default=False)),
                ('category_ids', models.JSONField(default=list)),
                ('breed_ids', models.JSONField(default=list)),
            ],
        ),
    ]
