# Generated by Django 5.2.6 on 2025-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatos',
            name='sub_id',
        ),
        migrations.AlterField(
            model_name='gatos',
            name='breed_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gatos',
            name='category_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gatos',
            name='has_breeds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gatos',
            name='url',
            field=models.URLField(),
        ),
    ]
